# Generated by Django 4.2.18 on 2025-04-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friend_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
