# Generated by Django 4.2.18 on 2025-04-29 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_friendrequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendRequest',
            new_name='GroupRequest',
        ),
    ]
