# Generated by Django 4.2.18 on 2025-04-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_rename_friendrequest_grouprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='origin_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
