# Generated by Django 4.2.18 on 2025-04-30 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_project_origin_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='origin_user_id',
        ),
        migrations.AddField(
            model_name='project',
            name='origin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='todo.user'),
        ),
    ]
