# Generated by Django 4.2.18 on 2025-04-30 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_remove_project_origin_user_id_project_origin_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
