# Generated by Django 5.2 on 2025-05-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_alter_grouprequest_to_user_alter_project_origin_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userforproject',
            name='avatar_path',
            field=models.CharField(default='avatars/avatar.png', max_length=255),
        ),
    ]
